import fs from 'fs';
import path from 'path';

const root = process.cwd();
const dictionaryPath = path.join(root, 'i18n', 'dictionary.json');
const outputDir = path.join(root, 'src', 'i18n');
const outputFile = path.join(outputDir, 'i18n.extended.ts');

if (!fs.existsSync(dictionaryPath)) {
  throw new Error(`Missing dictionary.json at ${dictionaryPath}`);
}

const dictionary = JSON.parse(fs.readFileSync(dictionaryPath, 'utf8'));
const defaultLocale = 'en-US';
const localeNames = {
  'en-US': 'English',
  'zh-CN': '简体中文',
  'zh-HK': '繁體中文',
  'zh-YUE': '粵語'
};

const requiredKeys = Object.keys(dictionary[defaultLocale] || {});
for (const [locale, entries] of Object.entries(dictionary)) {
  const missing = requiredKeys.filter((key) => !(key in entries));
  if (missing.length) {
    throw new Error(`Locale ${locale} is missing keys: ${missing.join(', ')}`);
  }
}

const banner = `// This file is auto-generated by scripts/generate-i18n.mjs.\n`;
const body = `${banner}` +
`import { Locale } from '@types';\n` +
`import { buildI18n } from './i18n.base';\n\n` +
`export const dictionary = ${JSON.stringify(dictionary, null, 2)} as const;\n` +
`export type LocaleKey = keyof typeof dictionary['${defaultLocale}'];\n` +
`export const localeNames: Record<Locale, string> = ${JSON.stringify(localeNames, null, 2)};\n` +
`export const supportedLocales = ${JSON.stringify(Object.keys(dictionary), null, 2)} as Locale[];\n` +
`export const i18n = buildI18n<LocaleKey>(dictionary, '${defaultLocale}', localeNames);\n` +
`export const t = i18n.t;\n`;

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(outputFile, body);
console.log(`i18n written to ${path.relative(root, outputFile)}`);
