name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congrats! You''ve made your first issue in RailMapMaker'
        pr-message: 'Congrats! You''ve made your first pr in RailMapMaker'
